---
- become: true
  service:
    name: "{{ firewall_sshd.name }}"
    state: restarted
    enabled: true
  changed_when: false

- name: Auto-detect ssh port.
  shell: 'lsof -i tcp -Pn 2>&1 | awk ''/sshd/ && /LISTEN/ { gsub(/.*:/,"",$(NF-1)) ; print $(NF-1) }'' | sort -u'
  become: true
  register: sshd_port
  when: firewall_ssh_port == -1
  changed_when: false
  failed_when: sshd_port.stdout is not regex("^[0-9]{2,5}$")

- name: Allow ssh connections on sshd listening port.
  become: true
  iptables:
    chain: INPUT
    protocol: tcp
    destination_port: "{{ sshd_port.stdout | default(firewall_ssh_port) }}"
    jump: ACCEPT
